name: Nightly UI Tests
on:
  push:
    branches:
      - feature/automated_tests

jobs:
  deploy:
    name: Run UI Tests
    runs-on: macos-13
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app/Contents/Developer'
    
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Setup Global Env
        run: |
          echo "SEED_PHRASE_1=${{ secrets.UITEST_SEED_PHRASE_1 }}" >> $GITHUB_ENV
          echo "SEED_PHRASE_PASSWORD=${{ secrets.UITEST_SEED_PHRASE_PASSWORD }}" >> $GITHUB_ENV
          echo "GMAIL_ADDRESS=${{ secrets.UITEST_GMAIL_ADDRESS }}" >> $GITHUB_ENV
          echo "GMAIL_PASSWORD=${{ secrets.UITEST_GMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Build and run tests
        run: |
          xcodebuild -project "Kukai Mobile.xcodeproj" \
          -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" \
          -scheme "Kukai Mobile Beta" \
          -resultBundlePath TestResults \
          -configuration Beta \
          -archivePath $PWD/build/Kukai-mobile.xcarchive \
          clean \
          archive \
          test \
          SEED_PHRASE_1="$SEED_PHRASE_1" \
          SEED_PHRASE_PASSWORD="$SEED_PHRASE_PASSWORD" \
          GMAIL_ADDRESS="$GMAIL_ADDRESS" \
          GMAIL_PASSWORD="$GMAIL_PASSWORD"

      - name: Install Sentry CLI
        if: ${{ success() || failure() }}
        run: brew install getsentry/tools/sentry-cli
      
      - name: Upload dSYM
        if: ${{ success() || failure() }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          export PATH=/usr/local/bin:$PATH
          export SENTRY_ORG=kukai
          export SENTRY_PROJECT=kukai-ios
          export CUSTOM_DSYM_PATH="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Kukai Mobile.app.dSYM"
          export CUSTOM_DSYM_PATH_FRAMEWORK="$PWD/build/Kukai-mobile.xcarchive/dSYMs/Sodium.framework.dSYM"
          
          echo "CUSTOM_DSYM_PATH: $CUSTOM_DSYM_PATH"
          echo "CUSTOM_DSYM_PATH_FRAMEWORK: $CUSTOM_DSYM_PATH_FRAMEWORK"
          
          ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH" 2>&1 >/dev/null)
          ERROR=$(sentry-cli upload-dif "$CUSTOM_DSYM_PATH_FRAMEWORK" 2>&1 >/dev/null)
          
          if [ ! $? -eq 0 ]; then
          echo "warning: sentry-cli - $ERROR"
          fi

      - uses: kishikawakatsumi/xcresulttool@v1.7.1
        if: ${{ success() || failure() }}
        with:
          path: TestResults.xcresult
