name: UI Tests
on:
  push:
    branches:
      - develop

# Self hosted runners seem to have trouble managing certs the way github hosted runners do
# So this job is setup expecting the certs to be installed on the machine and accessible to Xcode
jobs:
  deploy:
    name: Run UI Tests
    runs-on: self-hosted
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
        
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup Global Env
        run: |
          echo "CONFIG_1=${{ secrets.UITEST_CONFIG_1 }}" >> $GITHUB_ENV
          echo "CONFIG_2=${{ secrets.UITEST_CONFIG_2 }}" >> $GITHUB_ENV
          echo "CONFIG_3=${{ secrets.UITEST_CONFIG_3 }}" >> $GITHUB_ENV

      - name: Build and run tests
        run: |
          xcodebuild -project "Kukai Mobile.xcodeproj" \
          -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 16,OS=18.5" \
          -scheme "Kukai Mobile Beta" \
          -resultBundlePath TestResults \
          -configuration Beta \
          -archivePath $PWD/build/Kukai-mobile.xcarchive \
          -enableCodeCoverage YES \
          clean \
          archive \
          test \
          CONFIG_1="$CONFIG_1" \
          CONFIG_2="$CONFIG_2" \
          CONFIG_3="$CONFIG_3"

      - name: Upload xcresult file
        if: ${{ success() || failure() }}
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-${{ github.run_number }}.xcresult
          path: TestResults.xcresult
        
        # Run xcresultparser on the output file to generate a markdown summary
        # Grab the artifact URL from the previous step (new addtion to v4)
        # Use a bot webhook to post the details to slack, with a link to download the full thing if needed
        # Couldn't figure out how to upload the file directly to slack, the github action integration just sliently fails to everything without posting any error codes
      - name: Report to slack
        if: ${{ success() || failure() }}
        run: |
            xcr_markdown=$(xcresultparser --output-format txt --no-test-result --coverage --coverage-targets "Kukai" "TestResults-26.xcresult")
            curl -0 -v -X POST ${{ secrets.SLACK_INCOMING_WEBHOOK }} \
            -H "Expect:" \
            -H 'Content-Type: application/json; charset=utf-8' \
            --data-raw '
            {
                "blocks": [
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Automated UI test run complete\n\n'"${xcr_markdown}"'"
                        }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Download full file from runner <${{ steps.upload_artifact.outputs.artifact-url }}|Here>"
                        }
                    }
                ]
            }'
