name: Unit Test

on:
  pull_request:
    branches:
      - main
      - develop

# Checkout the code, and run mxcl's xcodebuild action to run the unit tests
jobs:
  build:
    runs-on: macos-11
    strategy:
      matrix:
        platform:
          - iOS
        xcode:
          - ^13
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: mxcl/xcodebuild@v1.9.2
        with:
          platform: ${{ matrix.platform }}
          xcode: ${{ matrix.xcode }}
          action: test
          code-coverage: true
          upload-logs: always
