name: Unit Test

on:
  pull_request:
    branches:
      - main
      - develop

# Checkout the code, and run mxcl's xcodebuild action to run the unit tests
jobs:
  build:
    name: Build and unit test
    runs-on: macos-latest
    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_13.3.app/Contents/Developer'

      - name: Checkout repository
        uses: actions/checkout@v2.3.5
        with:
          # PR's by default are pulled down as detached heads, meaning they can't be pushed back. Instead, checkout the actual branch, not the PR
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run Unit tests
        # If its not a lokalise PR, run unit tests
        if: ${{ !contains(github.head_ref, 'lokalise') }}
        run: xcodebuild -project "Kukai Mobile.xcodeproj" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' -scheme "Kukai Mobile Debug" test

      - name: For each localisation file, import to Xcode
         # If it is a lokalise PR, find and import all .xliff files, and commit changes
        if: ${{ contains(github.head_ref, 'lokalise') }}
        run: |
          find "$PWD/Kukai Mobile/Localization/Import" -type f -name "*.xliff" -maxdepth 1 | while read f ; do
            xcodebuild -importLocalizations -project "Kukai Mobile.xcodeproj" -localizationPath "$f" ;
          done

      - name: Commit changes
        if: ${{ success() && contains(github.head_ref, 'lokalise') }}
        run: |
          git add .
          git commit -m "CI: import lokalise updates"
          git push -u origin HEAD
        