name: Unit Test

on:
  pull_request:
    branches:
      - main
      - develop

# Checkout the code, and run mxcl's xcodebuild action to run the unit tests
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: mxcl/xcodebuild@v1.7.0
        with:
          platform: ${{ matrix.platform }}
          action: test
          code-coverage: true
          upload-logs: always